### ISSUE TITLE
click profile from post

### ISSUE THREAD

**Issue by saddington** [yenio/changelog#25]
clicking on the profile pic of the user that liked my post does not lead me to their profile.

https://beta.yen.io/outlawz/status/154059205659052

**Comment by saddington** [comment]
fixed.

**Comment by psherpa1** [comment]
https://beta.yen.io/Sherpa24/status/154203423581672
 issue still persist  for me. 
  any suggestions?
 thank you

**Comment by saddington** [comment]
@psherpa1 we're still working on this, for sure. we had wanted to get to it last sprint, but, worked much more on core features! love it! thanks for the help!
